-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2/5/2020 9:36:14 PM
-- Server version: 5.6.44-log
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set default database
--
USE mystoredb;

--
-- Definition for table staff
--
DROP TABLE IF EXISTS staff;
CREATE TABLE staff (
  id INT(20) NOT NULL AUTO_INCREMENT,
  fullname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  department VARCHAR(222) NOT NULL,
  address VARCHAR(222) NOT NULL,
  phonenumber VARCHAR(222) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE INDEX email (email),
  UNIQUE INDEX fullname (fullname)
)
ENGINE = INNODB
AUTO_INCREMENT = 11
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table staff_history
--
DROP TABLE IF EXISTS staff_history;
CREATE TABLE staff_history (
  id INT(20) NOT NULL AUTO_INCREMENT,
  product_id INT(12) NOT NULL,
  staff_id INT(12) NOT NULL,
  quantity VARCHAR(222) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table store
--
DROP TABLE IF EXISTS store;
CREATE TABLE store (
  id INT(20) NOT NULL AUTO_INCREMENT,
  productname VARCHAR(255) NOT NULL,
  quantity VARCHAR(255) NOT NULL,
  description VARCHAR(222) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE INDEX productname (productname)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table users
--
DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT(20) NOT NULL AUTO_INCREMENT,
  fullname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(222) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE INDEX email (email)
)
ENGINE = INNODB
AUTO_INCREMENT = 7
AVG_ROW_LENGTH = 3276
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Dumping data for table staff
--
INSERT INTO staff VALUES
(7, 'Kabera rukundo', 'kabera@gmail.com', 'karerangabo', 'Kigali', '78678678', '2020-02-05 11:43:24'),
(8, 'Karemera John', 'kamivi@gm.com', 'karurang', 'ldlkds', '032902390', '2020-02-05 11:48:35'),
(10, 'asdasd', 'asdasd', 'it', 'adasdasd', '234234', '2020-02-05 12:23:45');

-- 
-- Dumping data for table staff_history
--
INSERT INTO staff_history VALUES
(1, 1, 1, 'fd fd ', '2020-02-05 19:13:53');

-- 
-- Dumping data for table store
--
INSERT INTO store VALUES
(1, 'Laptop', '20', 'new laptops dubai', '2020-02-05 14:59:42');

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, 'kabera Jean', 'mugwales@gmail.com', 'password', '2020-02-03 21:45:40'),
(3, 'jhhj', 'jjkkj', 'lkkl', '2020-02-03 22:47:19'),
(4, 'geg', 'ergerg', 'gerg', '2020-02-03 22:56:25'),
(5, 'terter', '434234@dsdfd.comm', 'fgfg', '2020-02-03 23:06:12'),
(6, 'fdgdf', 'gdfg', 'fdg', '2020-02-04 00:53:16');

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;